### ISSUE TITLE
Response None values cause an exception

### ISSUE THREAD

**Issue by zyadsober1** [wael34218/python_openapi_generator#4]
When a response value is None, a KeyError: 'NoneType' exception is raised.

Example, consider this endpoint response:
```
{  
  "message":"Success",
  "data":[  
    {  
      "title":"basic list",
      "user_id":"133",
      "uri":"/end_point/1",
      "id":1,
      "description":null,
      "modified_date":"2019-03-13 10:41:20.357008",
      "created_date":"2019-03-13 10:41:20.357000"
    }
  ],
  "status":"OK",
  "code":200
}
```
It raises an Exception such as:
```
Traceback (most recent call last):
  File "shopping_list/script.py", line 100, in <module>
    generate_docs(pages)
  File "shopping_list/script.py", line 44, in generate_docs
    gen.add_response(response, description=page.description)
  File "/media/ubuntu/DATA/git/venv/some-app/lib/python3.5/site-packages/openapi_generator/openapi_generator.py", line 45, in add_response
    responses = self._get_response(response)
  File "/media/ubuntu/DATA/git/venv/some-app/lib/python3.5/site-packages/openapi_generator/openapi_generator.py", line 182, in _get_response
    for k, v in response.json().items()
  File "/media/ubuntu/DATA/git/venv/some-app/lib/python3.5/site-packages/openapi_generator/openapi_generator.py", line 182, in <dictcomp>
    for k, v in response.json().items()
  File "/media/ubuntu/DATA/git/venv/some-app/lib/python3.5/site-packages/openapi_generator/openapi_generator.py", line 115, in _get_props
    properties.append(OpenapiGenerator._get_props(i))
  File "/media/ubuntu/DATA/git/venv/some-app/lib/python3.5/site-packages/openapi_generator/openapi_generator.py", line 122, in _get_props
    props['properties'] = {k: OpenapiGenerator._get_props(v) for k, v in item.items()}
  File "/media/ubuntu/DATA/git/venv/some-app/lib/python3.5/site-packages/openapi_generator/openapi_generator.py", line 122, in <dictcomp>
    props['properties'] = {k: OpenapiGenerator._get_props(v) for k, v in item.items()}
  File "/media/ubuntu/DATA/git/venv/some-app/lib/python3.5/site-packages/openapi_generator/openapi_generator.py", line 107, in _get_props
    props = {'type': OpenapiGenerator.types_map[item.__class__.__name__]}
KeyError: 'NoneType'
```

**Comment by wael34218** [comment]
OpenAPI data types are limited to:
```
string
number.
integer.
boolean.
array.
object.
```
So it cannot handle None/Null types. The fix committed interprets `None` as `string`. OpenAPI also assumes dates and files are strings so this should be ok.
